# Generated by Django 2.2 on 2020-06-15 12:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=100, verbose_name='Post Title')),
                ('description', models.TextField(verbose_name='Post Description')),
                ('posted_date', models.DateField(default=datetime.date.today)),
                ('good_name', models.CharField(max_length=100, verbose_name='Good Name')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.User')),
            ],
        ),
    ]
